// SigortamRahat - Sigorta Çapraz Satış KDS Kapsamlı Veritabanı (100+ Meslek // Kural Motoru)
const DEFAULT_DB = {
    JOBS: [
        { MESLEK_NO: 1, MESLEK: "Avukat", RISK_SKORU: 8, ETIKETLER: "HUKUK, OFIS, SORUMLULUK, STRES" },
        { MESLEK_NO: 2, MESLEK: "Doktor (Cerrah)", RISK_SKORU: 10, ETIKETLER: "SAGLIK, SORUMLULUK, YUKSEK_GELIR, STRES" },
        { MESLEK_NO: 3, MESLEK: "Yazılım Mühendisi", RISK_SKORU: 3, ETIKETLER: "OFIS, ELEKTRONIK, HAREKETSIZ, HOME_OFFICE" },
        { MESLEK_NO: 4, MESLEK: "Motosiklet Kuryesi", RISK_SKORU: 9, ETIKETLER: "TRAFIK, BEDENSEL, DIS_SAHA, ACILIYET, KAZA_RISKI" },
        { MESLEK_NO: 5, MESLEK: "Tır / Kamyon Şoförü", RISK_SKORU: 9, ETIKETLER: "TRAFIK, ULUSLARARASI, BEDENSEL, DIS_SAHA, KAZA_RISKI" },
        { MESLEK_NO: 6, MESLEK: "Mali Müşavir", RISK_SKORU: 5, ETIKETLER: "OFIS, FINANS, SORUMLULUK, STRES" },
        { MESLEK_NO: 7, MESLEK: "İnşaat Mühendisi", RISK_SKORU: 7, ETIKETLER: "INSAAT, SAHA_DENETIM, SORUMLULUK, PROJE" },
        { MESLEK_NO: 8, MESLEK: "Esnaf (Bakkal/Market)", RISK_SKORU: 6, ETIKETLER: "TICARET, ISYERI, NAKIT_RISKI, HALKLA_ILISKILER" },
        { MESLEK_NO: 9, MESLEK: "Mimar", RISK_SKORU: 5, ETIKETLER: "OFIS, SAHA_DENETIM, PROJE, ELEKTRONIK" },
        { MESLEK_NO: 10, MESLEK: "Öğretmen", RISK_SKORU: 4, ETIKETLER: "KAMU, SORUMLULUK, STRES, KALABALIK" },
        { MESLEK_NO: 11, MESLEK: "Bankacı / Portföy Yöneticisi", RISK_SKORU: 4, ETIKETLER: "FINANS, OFIS, NAKIT_RISKI, STRES" },
        { MESLEK_NO: 12, MESLEK: "Diş Hekimi", RISK_SKORU: 8, ETIKETLER: "SAGLIK, SORUMLULUK, ISYERI, PAHALI_CIHAZ, ENFEKSIYON" },
        { MESLEK_NO: 13, MESLEK: "Fabrika İşçisi (Metal/Ağır Sanayi)", RISK_SKORU: 8, ETIKETLER: "URETIM, BEDENSEL, KAZA_RISKI, VARDIYA" },
        { MESLEK_NO: 14, MESLEK: "Eczacı", RISK_SKORU: 5, ETIKETLER: "SAGLIK, TICARET, ISYERI, SORUMLULUK" },
        { MESLEK_NO: 15, MESLEK: "Gayrimenkul Danışmanı", RISK_SKORU: 5, ETIKETLER: "SATIS, DIS_SAHA, TRAFIK, TICARET" },
        { MESLEK_NO: 16, MESLEK: "Pilot (Havayolu)", RISK_SKORU: 7, ETIKETLER: "ULUSLARARASI, YUKSEK_GELIR, OZEL_RISK, STRES, SEYAHAT" },
        { MESLEK_NO: 17, MESLEK: "Grafik & UI/UX Tasarımcı", RISK_SKORU: 2, ETIKETLER: "OFIS, ELEKTRONIK, HAREKETSIZ, FREELANCE" },
        { MESLEK_NO: 18, MESLEK: "Güvenlik Görevlisi", RISK_SKORU: 7, ETIKETLER: "KORUMA, VARDIYA, DIS_SAHA, STRES, GUVENLIK" },
        { MESLEK_NO: 19, MESLEK: "Satış Temsilcisi (Saha)", RISK_SKORU: 6, ETIKETLER: "SATIS, TRAFIK, DIS_SAHA, STRES" },
        { MESLEK_NO: 20, MESLEK: "Veteriner Hekim", RISK_SKORU: 7, ETIKETLER: "SAGLIK, HAYVAN_RISKI, ISYERI, SORUMLULUK" },
        { MESLEK_NO: 21, MESLEK: "Hemşire / Sağlık Teknisyeni", RISK_SKORU: 6, ETIKETLER: "SAGLIK, VARDIYA, BEDENSEL, STRES, ENFEKSIYON" },
        { MESLEK_NO: 22, MESLEK: "Polis Memuru / Emniyet Personeli", RISK_SKORU: 9, ETIKETLER: "GUVENLIK, DIS_SAHA, SILAH_RISKI, STRES, VARDIYA, KAZA_RISKI" },
        { MESLEK_NO: 23, MESLEK: "İtfaiyeci / Arama Kurtarma", RISK_SKORU: 10, ETIKETLER: "YUKSEK_RISK, BEDENSEL, DIS_SAHA, HAYATI_TEHLIKE, KAZA_RISKI" },
        { MESLEK_NO: 24, MESLEK: "Aşçı / Executive Chef", RISK_SKORU: 7, ETIKETLER: "MUTFAK, KESICI_ALET, YANIK_RISKI, ISYERI, VARDIYA" },
        { MESLEK_NO: 25, MESLEK: "Garson / Servis Elemanı", RISK_SKORU: 4, ETIKETLER: "HIZMET, BEDENSEL, YOGUN_TEMPO, VARDIYA" },
        { MESLEK_NO: 26, MESLEK: "Elektrik & Elektronik Mühendisi", RISK_SKORU: 6, ETIKETLER: "SAHA_DENETIM, ELEKTRIK, SORUMLULUK, PROJE" },
        { MESLEK_NO: 27, MESLEK: "Elektrik Teknisyeni / Tesisatçı", RISK_SKORU: 8, ETIKETLER: "ELEKTRIK, YUKSEKTE_CALISMA, BEDENSEL, KAZA_RISKI, DIS_SAHA" },
        { MESLEK_NO: 28, MESLEK: "Gemi Kaptanı / Denizci", RISK_SKORU: 8, ETIKETLER: "DENIZ, ULUSLARARASI, YUKSEK_RISK, DIS_SAHA, OZEL_RISK" },
        { MESLEK_NO: 29, MESLEK: "Taksi / Dolmuş Şoförü", RISK_SKORU: 8, ETIKETLER: "TRAFIK, STRES, DIS_SAHA, NAKIT_RISKI, KAZA_RISKI" },
        { MESLEK_NO: 30, MESLEK: "Akademisyen / Profesör", RISK_SKORU: 3, ETIKETLER: "KAMU, OFIS, HAREKETSIZ, SEYAHAT" },
        { MESLEK_NO: 31, MESLEK: "Noter", RISK_SKORU: 6, ETIKETLER: "HUKUK, OFIS, SORUMLULUK, NAKIT_RISKI" },
        { MESLEK_NO: 32, MESLEK: "Kuaför / Güzellik Uzmanı", RISK_SKORU: 5, ETIKETLER: "HIZMET, ISYERI, BEDENSEL, KIMYASAL_TEMAS" },
        { MESLEK_NO: 33, MESLEK: "Kuyumcu / Sarraf", RISK_SKORU: 9, ETIKETLER: "TICARET, ISYERI, YUKSEK_DEGER, HIRSIZLIK_RISKI, NAKIT_RISKI" },
        { MESLEK_NO: 34, MESLEK: "Restoran / Kafe İşletmecisi", RISK_SKORU: 7, ETIKETLER: "TICARET, ISYERI, MUTFAK, SORUMLULUK, NAKIT_RISKI" },
        { MESLEK_NO: 35, MESLEK: "Oto Tamir & Bakım Ustası", RISK_SKORU: 8, ETIKETLER: "SANAYI, BEDENSEL, KAZA_RISKI, ISYERI, YANIK_RISKI" },
        { MESLEK_NO: 36, MESLEK: "Fizyoterapist", RISK_SKORU: 4, ETIKETLER: "SAGLIK, BEDENSEL, HIZMET, SORUMLULUK" },
        { MESLEK_NO: 37, MESLEK: "Diyetisyen / Beslenme Uzmanı", RISK_SKORU: 3, ETIKETLER: "SAGLIK, OFIS, HIZMET" },
        { MESLEK_NO: 38, MESLEK: "Psikolog / Terapist", RISK_SKORU: 4, ETIKETLER: "SAGLIK, OFIS, STRES, SORUMLULUK" },
        { MESLEK_NO: 39, MESLEK: "Kaynakçı / Metal İmalatçısı", RISK_SKORU: 9, ETIKETLER: "SANAYI, YANIK_RISKI, KAZA_RISKI, BEDENSEL, GOZ_RISKI" },
        { MESLEK_NO: 40, MESLEK: "Vinç / İş Makinesi Operatörü", RISK_SKORU: 9, ETIKETLER: "INSAAT, AGIR_VASITA, KAZA_RISKI, DIS_SAHA, OZEL_RISK" },
        { MESLEK_NO: 41, MESLEK: "Maden Mühendisi / Madenci", RISK_SKORU: 10, ETIKETLER: "MADEN, YUKSEK_RISK, BEDENSEL, DIS_SAHA, HAYATI_TEHLIKE" },
        { MESLEK_NO: 42, MESLEK: "Ziraat Mühendisi / Tarım İşletmecisi", RISK_SKORU: 6, ETIKETLER: "TARIM, DIS_SAHA, PROJE, TICARET" },
        { MESLEK_NO: 43, MESLEK: "Çiftçi / Hayvancılık İşletmecisi", RISK_SKORU: 7, ETIKETLER: "TARIM, HAYVAN_RISKI, BEDENSEL, DIS_SAHA, DOGAL_AFET" },
        { MESLEK_NO: 44, MESLEK: "Kabin Memuru (Hostes/Host)", RISK_SKORU: 6, ETIKETLER: "ULUSLARARASI, SEYAHAT, BEDENSEL, STRES, OZEL_RISK" },
        { MESLEK_NO: 45, MESLEK: "Hava Trafik Kontrolörü", RISK_SKORU: 8, ETIKETLER: "STRES, SORUMLULUK, OFIS, ELEKTRONIK" },
        { MESLEK_NO: 46, MESLEK: "Gümrük Müşaviri", RISK_SKORU: 6, ETIKETLER: "FINANS, OFIS, HUKUK, ULUSLARARASI, TICARET" },
        { MESLEK_NO: 47, MESLEK: "Fotoğrafçı / Kameraman", RISK_SKORU: 4, ETIKETLER: "PAHALI_CIHAZ, ELEKTRONIK, DIS_SAHA, FREELANCE" },
        { MESLEK_NO: 48, MESLEK: "Ses / Görüntü Prodüktörü", RISK_SKORU: 3, ETIKETLER: "OFIS, ELEKTRONIK, PAHALI_CIHAZ, STRES" },
        { MESLEK_NO: 49, MESLEK: "İç Mimar & Dekoratör", RISK_SKORU: 5, ETIKETLER: "SAHA_DENETIM, PROJE, OFIS, TICARET" },
        { MESLEK_NO: 50, MESLEK: "Peyzaj Mimarı", RISK_SKORU: 5, ETIKETLER: "DIS_SAHA, PROJE, SAHA_DENETIM, TARIM" },
        { MESLEK_NO: 51, MESLEK: "Kimyager / Laboratuvar Uzmanı", RISK_SKORU: 7, ETIKETLER: "KIMYASAL_TEMAS, SAGLIK, URETIM, SORUMLULUK" },
        { MESLEK_NO: 52, MESLEK: "Biyolog / Genetik Uzmanı", RISK_SKORU: 5, ETIKETLER: "SAGLIK, OFIS, ENFEKSIYON, ELEKTRONIK" },
        { MESLEK_NO: 53, MESLEK: "Aktüer / Risk Analisti", RISK_SKORU: 2, ETIKETLER: "FINANS, OFIS, ELEKTRONIK, HAREKETSIZ" },
        { MESLEK_NO: 54, MESLEK: "Sigorta Acentesi / Broker", RISK_SKORU: 4, ETIKETLER: "FINANS, OFIS, TICARET, SATIS" },
        { MESLEK_NO: 55, MESLEK: "Lojistik & Tedarik Zinciri Müdürü", RISK_SKORU: 5, ETIKETLER: "OFIS, ULUSLARARASI, TICARET, PROJE" },
        { MESLEK_NO: 56, MESLEK: "Depo / Antrepo Görevlisi", RISK_SKORU: 7, ETIKETLER: "SANAYI, BEDENSEL, KAZA_RISKI, VARDIYA" },
        { MESLEK_NO: 57, MESLEK: "Kargo Dağıtım Şoförü", RISK_SKORU: 8, ETIKETLER: "TRAFIK, BEDENSEL, DIS_SAHA, STRES, KAZA_RISKI" },
        { MESLEK_NO: 58, MESLEK: "Boyacı / Sıvacı / İnşaat Ustası", RISK_SKORU: 9, ETIKETLER: "INSAAT, YUKSEKTE_CALISMA, BEDENSEL, KAZA_RISKI" },
        { MESLEK_NO: 59, MESLEK: "Çatı & Cephe Kaplama Ustası", RISK_SKORU: 10, ETIKETLER: "INSAAT, YUKSEKTE_CALISMA, HAYATI_TEHLIKE, BEDENSEL" },
        { MESLEK_NO: 60, MESLEK: "Mobilya İmalatçısı / Marangoz", RISK_SKORU: 8, ETIKETLER: "SANAYI, KESICI_ALET, ISYERI, KAZA_RISKI" },
        { MESLEK_NO: 61, MESLEK: "Gözlükçü / Optisyen", RISK_SKORU: 4, ETIKETLER: "SAGLIK, TICARET, ISYERI, PAHALI_CIHAZ" },
        { MESLEK_NO: 62, MESLEK: "Medikal Cihaz Satış Uzmanı", RISK_SKORU: 5, ETIKETLER: "SAGLIK, SATIS, TRAFIK, TICARET" },
        { MESLEK_NO: 63, MESLEK: "Girişimci / Startup Kurucusu", RISK_SKORU: 5, ETIKETLER: "TICARET, OFIS, STRES, YUKSEK_GELIR, ELEKTRONIK" },
        { MESLEK_NO: 64, MESLEK: "CEO / Üst Düzey Yönetici", RISK_SKORU: 6, ETIKETLER: "YUKSEK_GELIR, SORUMLULUK, STRES, SEYAHAT, OFIS" },
        { MESLEK_NO: 65, MESLEK: "İnsan Kaynakları Uzmanı", RISK_SKORU: 3, ETIKETLER: "OFIS, HAREKETSIZ, SORUMLULUK" },
        { MESLEK_NO: 66, MESLEK: "Pazarlama & Marka Direktörü", RISK_SKORU: 4, ETIKETLER: "OFIS, STRES, SEYAHAT, ELEKTRONIK" },
        { MESLEK_NO: 67, MESLEK: "Sosyal Medya Yöneticisi / Influencer", RISK_SKORU: 3, ETIKETLER: "ELEKTRONIK, FREELANCE, OFIS, SEYAHAT" },
        { MESLEK_NO: 68, MESLEK: "E-Ticaret Mağaza Sahibi", RISK_SKORU: 5, ETIKETLER: "TICARET, ELEKTRONIK, ISYERI, NAKIT_RISKI" },
        { MESLEK_NO: 69, MESLEK: "Çevirmen / Tercüman", RISK_SKORU: 2, ETIKETLER: "OFIS, HOME_OFFICE, FREELANCE, HAREKETSIZ" },
        { MESLEK_NO: 70, MESLEK: "Gazeteci / Muhabir (Saha)", RISK_SKORU: 8, ETIKETLER: "DIS_SAHA, SEYAHAT, STRES, OZEL_RISK, PAHALI_CIHAZ" },
        { MESLEK_NO: 71, MESLEK: "Profesyonel Sporcu / Antrenör", RISK_SKORU: 8, ETIKETLER: "BEDENSEL, KAZA_RISKI, OZEL_RISK, SEYAHAT" },
        { MESLEK_NO: 72, MESLEK: "Fitness Eğitmeni / Personal Trainer", RISK_SKORU: 5, ETIKETLER: "BEDENSEL, HIZMET, SAGLIK" },
        { MESLEK_NO: 73, MESLEK: "Tur Rehberi / Turizm Operatörü", RISK_SKORU: 6, ETIKETLER: "ULUSLARARASI, SEYAHAT, DIS_SAHA, HIZMET" },
        { MESLEK_NO: 74, MESLEK: "Otel Müdürü / Yönetici", RISK_SKORU: 5, ETIKETLER: "HIZMET, ISYERI, SORUMLULUK, TICARET" },
        { MESLEK_NO: 75, MESLEK: "Vali / Kaymakam / Bürokrat", RISK_SKORU: 6, ETIKETLER: "KAMU, SORUMLULUK, STRES, GUVENLIK" },
        { MESLEK_NO: 76, MESLEK: "Hakim / Savcı", RISK_SKORU: 8, ETIKETLER: "HUKUK, KAMU, SORUMLULUK, STRES, GUVENLIK" },
        { MESLEK_NO: 77, MESLEK: "Asker / Subay / Astsubay", RISK_SKORU: 10, ETIKETLER: "GUVENLIK, DIS_SAHA, SILAH_RISKI, HAYATI_TEHLIKE, OZEL_RISK" },
        { MESLEK_NO: 78, MESLEK: "Gümrük Muhafaza Memuru", RISK_SKORU: 8, ETIKETLER: "GUVENLIK, DIS_SAHA, VARDIYA, STRES" },
        { MESLEK_NO: 79, MESLEK: "Orman Mühendisi / Muhafaza Memuru", RISK_SKORU: 8, ETIKETLER: "DIS_SAHA, YUKSEK_RISK, KAZA_RISKI, DOGAL_AFET" },
        { MESLEK_NO: 80, MESLEK: "Çevre Mühendisi", RISK_SKORU: 5, ETIKETLER: "SAHA_DENETIM, PROJE, OFIS, SANAYI" },
        { MESLEK_NO: 81, MESLEK: "Gıda Mühendisi / Kalite Denetçisi", RISK_SKORU: 5, ETIKETLER: "URETIM, SANAYI, SORUMLULUK, SAHA_DENETIM" },
        { MESLEK_NO: 82, MESLEK: "Tekstil / Konfeksiyon İmalatçısı", RISK_SKORU: 7, ETIKETLER: "SANAYI, ISYERI, TICARET, YANGIN_RISKI" },
        { MESLEK_NO: 83, MESLEK: "Matbaa / Basım Operatörü", RISK_SKORU: 7, ETIKETLER: "SANAYI, KESICI_ALET, ISYERI, KIMYASAL_TEMAS" },
        { MESLEK_NO: 84, MESLEK: "Kuru Temizleme / Yıkama İşletmecisi", RISK_SKORU: 6, ETIKETLER: "ISYERI, TICARET, KIMYASAL_TEMAS, YANGIN_RISKI" },
        { MESLEK_NO: 85, MESLEK: "Fırıncı / Unlu Mamuller Ustası", RISK_SKORU: 7, ETIKETLER: "MUTFAK, YANIK_RISKI, ISYERI, TICARET, VARDIYA" },
        { MESLEK_NO: 86, MESLEK: "Kasap / Et İşleme Uzmanı", RISK_SKORU: 8, ETIKETLER: "KESICI_ALET, ISYERI, TICARET, KAZA_RISKI" },
        { MESLEK_NO: 87, MESLEK: "Balıkçı / Su Ürünleri Üreticisi", RISK_SKORU: 9, ETIKETLER: "DENIZ, BEDENSEL, YUKSEK_RISK, DIS_SAHA" },
        { MESLEK_NO: 88, MESLEK: "Dalgıç / Sualtı Sanayi Personeli", RISK_SKORU: 10, ETIKETLER: "DENIZ, YUKSEK_RISK, HAYATI_TEHLIKE, OZEL_RISK" },
        { MESLEK_NO: 89, MESLEK: "Yat Kaptanı / Marina Görevlisi", RISK_SKORU: 6, ETIKETLER: "DENIZ, YUKSEK_GELIR, HIZMET, OZEL_RISK" },
        { MESLEK_NO: 90, MESLEK: "Vale / Otopark Görevlisi", RISK_SKORU: 6, ETIKETLER: "TRAFIK, ARAC, BEDENSEL, DIS_SAHA" },
        { MESLEK_NO: 91, MESLEK: "Temizlik & Tesis Hizmetleri Elemanı", RISK_SKORU: 5, ETIKETLER: "BEDENSEL, KIMYASAL_TEMAS, HIZMET, VARDIYA" },
        { MESLEK_NO: 92, MESLEK: "Cam Temizlik Ustası (Gökdelen/Dış Cephe)", RISK_SKORU: 10, ETIKETLER: "YUKSEKTE_CALISMA, HAYATI_TEHLIKE, BEDENSEL, KAZA_RISKI" },
        { MESLEK_NO: 93, MESLEK: "Doğalgaz / Isıtma Tesisatçısı", RISK_SKORU: 8, ETIKETLER: "DIS_SAHA, BEDENSEL, KAZA_RISKI, YANGIN_RISKI" },
        { MESLEK_NO: 94, MESLEK: "Asansör Bakım & Montaj Teknisyeni", RISK_SKORU: 9, ETIKETLER: "YUKSEKTE_CALISMA, KAZA_RISKI, ELEKTRIK, SANAYI" },
        { MESLEK_NO: 95, MESLEK: "Güneş Enerjisi (GES) Kurulum Uzmanı", RISK_SKORU: 8, ETIKETLER: "YUKSEKTE_CALISMA, ELEKTRIK, DIS_SAHA, INSAAT" },
        { MESLEK_NO: 96, MESLEK: "Rüzgar Türbini Teknisyeni", RISK_SKORU: 10, ETIKETLER: "YUKSEKTE_CALISMA, HAYATI_TEHLIKE, ELEKTRIK, DIS_SAHA" },
        { MESLEK_NO: 97, MESLEK: "Otomotiv Satış Bayisi / Galeri Sahibi", RISK_SKORU: 7, ETIKETLER: "TICARET, ARAC, YUKSEK_DEGER, NAKIT_RISKI" },
        { MESLEK_NO: 98, MESLEK: "Antikacı / Sanat Galerisi Sahibi", RISK_SKORU: 6, ETIKETLER: "TICARET, YUKSEK_DEGER, ISYERI, HIRSIZLIK_RISKI" },
        { MESLEK_NO: 99, MESLEK: "Müzisyen / Sahne Sanatçısı", RISK_SKORU: 5, ETIKETLER: "FREELANCE, PAHALI_CIHAZ, SEYAHAT, OZEL_RISK" },
        { MESLEK_NO: 100, MESLEK: "Sinema / Dizi Oyuncusu", RISK_SKORU: 6, ETIKETLER: "YUKSEK_GELIR, STRES, SEYAHAT, OZEL_RISK" },
        { MESLEK_NO: 101, MESLEK: "Yazar / Senarist / Editör", RISK_SKORU: 2, ETIKETLER: "OFIS, HOME_OFFICE, ELEKTRONIK, HAREKETSIZ" },
        { MESLEK_NO: 102, MESLEK: "Siber Güvenlik Uzmanı / Penetrasyon Testçisi", RISK_SKORU: 3, ETIKETLER: "OFIS, ELEKTRONIK, HOME_OFFICE, SORUMLULUK" },
        { MESLEK_NO: 103, MESLEK: "Veri Bilimci / Yapay Zeka Mühendisi", RISK_SKORU: 3, ETIKETLER: "OFIS, ELEKTRONIK, HOME_OFFICE, FINANS" },
        { MESLEK_NO: 104, MESLEK: "Bulut Mimarı / DevOps Mühendisi", RISK_SKORU: 3, ETIKETLER: "OFIS, ELEKTRONIK, SORUMLULUK, STRES" },
        { MESLEK_NO: 105, MESLEK: "Emekli (Sosyal Güvenlik)", RISK_SKORU: 5, ETIKETLER: "YASLI, SAGLIK, KONUT, HAREKETSIZ" },
        { MESLEK_NO: 106, MESLEK: "Üniversite Öğrencisi", RISK_SKORU: 2, ETIKETLER: "GENC, OGRENCI_RISK, ELEKTRONIK, SEYAHAT" },
        { MESLEK_NO: 107, MESLEK: "Ev Hanımı / Ev Yöneticisi", RISK_SKORU: 3, ETIKETLER: "KONUT, ESYA, SAGLIK, COCUK" }
    ],

    ASSETS: [
        { VARLIK_KODU: "A1", VARLIK_ADI: "Binek Otomobil", EK_ETIKET: "TRAFIK, ARAC, KASKO_IHTIYAC" },
        { VARLIK_KODU: "A2", VARLIK_ADI: "Motosiklet / Scooter", EK_ETIKET: "TRAFIK, MOTOR_RISK, BEDENSEL, KAZA_RISKI" },
        { VARLIK_KODU: "A3", VARLIK_ADI: "Ticari Araç / Panelvan", EK_ETIKET: "TRAFIK, ARAC, TICARET, DIS_SAHA" },
        { VARLIK_KODU: "A4", VARLIK_ADI: "Kendi Evi (Tapulu Mülk)", EK_ETIKET: "KONUT, DEPREM, MULK_SAHIBI, YANGIN_RISKI" },
        { VARLIK_KODU: "A5", VARLIK_ADI: "Kira Evi (Kiracı)", EK_ETIKET: "ESYA, DEPREM, KIRACI, YANGIN_RISKI" },
        { VARLIK_KODU: "A6", VARLIK_ADI: "Yazlık / Dağ Evi", EK_ETIKET: "KONUT, DEPREM, EK_MULK, HIRSIZLIK_RISKI" },
        { VARLIK_KODU: "A7", VARLIK_ADI: "Dükkan / Ofis / İş Yeri Mülkü", EK_ETIKET: "ISYERI, TICARET, SORUMLULUK, YANGIN_RISKI" },
        { VARLIK_KODU: "A8", VARLIK_ADI: "Yüksek Değerli Elektronik / Bilgisayar Seti", EK_ETIKET: "ELEKTRONIK, PAHALI_CIHAZ, OFIS" },
        { VARLIK_KODU: "A9", VARLIK_ADI: "Evcil Hayvan (Kedi/Köpek)", EK_ETIKET: "PATI, SAGLIK, HAYVAN_RISKI" },
        { VARLIK_KODU: "A10", VARLIK_ADI: "Sık Yurt Dışı Seyahati / Tatil", EK_ETIKET: "ULUSLARARASI, SEYAHAT, VIZEDESTEK" },
        { VARLIK_KODU: "A11", VARLIK_ADI: "Tekne / Yat / Deniz Taşıtı", EK_ETIKET: "DENIZ, YUKSEK_GELIR, OZEL_RISK" },
        { VARLIK_KODU: "A12", VARLIK_ADI: "Değerli Takı / Sanat Eseri Koleksiyonu", EK_ETIKET: "YUKSEK_DEGER, HIRSIZLIK_RISKI, YUKSEK_GELIR" },
        { VARLIK_KODU: "A13", VARLIK_ADI: "Bebek / Okul Çağında Çocuk", EK_ETIKET: "COCUK, SAGLIK, SORUMLULUK" },
        { VARLIK_KODU: "A14", VARLIK_ADI: "Ekstrem Spor / Doğa Sporları Hobisi", EK_ETIKET: "YUKSEK_RISK, KAZA_RISKI, OZEL_RISK" },
        { VARLIK_KODU: "A15", VARLIK_ADI: "Güneş Enerjisi (Çatı GES Panelleri)", EK_ETIKET: "ELEKTRIK, KONUT, PAHALI_CIHAZ" }
    ],

    PRODUCTS: [
        { URUN_ID: "P1", URUN_ADI: "Tamamlayıcı Sağlık Sigortası (TSS)", HEDEF_ETIKETLER: "SAGLIK, YASLI, BEDENSEL, STRES, ENFEKSIYON, COCUK", SATIS_ARGUMANI: "SGK anlaşmalı özel hastanelerde fark ücreti ödemeden modern tedavi güvencesi." },
        { URUN_ID: "P2", URUN_ADI: "Özel Sağlık Sigortası (ÖSS)", HEDEF_ETIKETLER: "YUKSEK_GELIR, SAGLIK, COCUK, OZEL_RISK, SEYAHAT", SATIS_ARGUMANI: "En seçkin A+ hastanelerde sınırsız yatarak/ayakta tedavi ve yurt dışı teminat konforu." },
        { URUN_ID: "P3", URUN_ADI: "Kapsamlı Genişletilmiş Kasko", HEDEF_ETIKETLER: "TRAFIK, ARAC, KASKO_IHTIYAC, DIS_SAHA, YUKSEK_DEGER", SATIS_ARGUMANI: "Çarpma, çalınma, doğal afet, terör ve orijinal yedek parça değişim garantisi." },
        { URUN_ID: "P4", URUN_ADI: "Zorunlu Trafik Sigortası", HEDEF_ETIKETLER: "TRAFIK, ARAC, MOTOR_RISK", SATIS_ARGUMANI: "Karşı tarafa ve üçüncü şahıslara verilebilecek bedeni ve maddi zararlara yasal kalkan." },
        { URUN_ID: "P5", URUN_ADI: "Konut & Eşya Paket Sigortası", HEDEF_ETIKETLER: "KONUT, ESYA, MULK_SAHIBI, KIRACI, YANGIN_RISKI, DEPREM", SATIS_ARGUMANI: "Yangın, su basması, hırsızlık, elektronik eşya ve komşuluk mali sorumluluk koruması." },
        { URUN_ID: "P6", URUN_ADI: "DASK (Zorunlu Deprem Sigortası)", HEDEF_ETIKETLER: "DEPREM, KONUT, MULK_SAHIBI, EK_MULK", SATIS_ARGUMANI: "Deprem ve deprem kaynaklı yangın, tsunami ve yer kaymasına karşı zorunlu devlet teminatı." },
        { URUN_ID: "P7", URUN_ADI: "Mesleki Sorumluluk Sigortası", HEDEF_ETIKETLER: "SORUMLULUK, HUKUK, SAGLIK, FINANS, PROJE, SAHA_DENETIM", SATIS_ARGUMANI: "Mesleğinizi icra ederken oluşabilecek ihmal, hata ve tazminat taleplerine tam koruma." },
        { URUN_ID: "P8", URUN_ADI: "Ferdi Kaza & Yaşam Güvencesi", HEDEF_ETIKETLER: "BEDENSEL, YUKSEK_RISK, KAZA_RISKI, GUVENLIK, DIS_SAHA, HAYATI_TEHLIKE", SATIS_ARGUMANI: "Beklenmedik kazalara karşı vefat, sürekli sakatlık ve gündelik iş göremezlik desteği." },
        { URUN_ID: "P9", URUN_ADI: "KOBİ / İş Yeri Paket Sigortası", HEDEF_ETIKETLER: "ISYERI, TICARET, NAKIT_RISKI, URETIM, SANAYI, YANGIN_RISKI", SATIS_ARGUMANI: "İş yeri binası, demirbaşlar, emtia stokları, iş durması ve 3. şahıs mali mesuliyet paketi." },
        { URUN_ID: "P10", URUN_ADI: "Yurt Dışı Seyahat Sağlık Sigortası", HEDEF_ETIKETLER: "ULUSLARARASI, SEYAHAT, VIZEDESTEK", SATIS_ARGUMANI: "Schengen ve dünya genelinde acil tıbbi tedavi, bagaj kaybı ve vize zorunluluk uyumu." },
        { URUN_ID: "P11", URUN_ADI: "Elektronik Cihaz & Siber Koruma", HEDEF_ETIKETLER: "ELEKTRONIK, PAHALI_CIHAZ, OFIS, HOME_OFFICE, FREELANCE", SATIS_ARGUMANI: "Dizüstü bilgisayarlar, tabletler ve profesyonel cihazlar için kazaen kırılma ve sıvı teması koruması." },
        { URUN_ID: "P12", URUN_ADI: "Pati / Evcil Hayvan Sağlık Sigortası", HEDEF_ETIKETLER: "PATI, HAYVAN_RISKI", SATIS_ARGUMANI: "Kedi ve köpekler için acil ameliyat, yatarak tedavi muayeneleri ve aşı takip avantajları." },
        { URUN_ID: "P13", URUN_ADI: "Tekne / Yat Gövde (Tekne Kasko) Sigortası", HEDEF_ETIKETLER: "DENIZ, YUKSEK_GELIR, OZEL_RISK", SATIS_ARGUMANI: "Deniz kaza riskleri, fırtına, batma, yangın ve marina sorumluluklarına kapsamlı teminat." }
    ]
};